@base = http://localhost:5000/
@a_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbHVib3JlQGdtYWlsLmNvbSIsInVzZXJJZCI6NCwiaWF0IjoxNjc3NDMzNTc1LCJleHAiOjE2Nzc1MTk5NzV9.5V0VnEJ400eFXlQ5zzYrPXWs1yhm1_oMrLiXlJUVwc0
@r_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbHVib3JlQGdtYWlsLmNvbSIsInVzZXJJZCI6NCwiaWF0IjoxNjc3NDMzNTc1LCJleHAiOjE2Nzc1MTk5NzV9.wUbHCo4pUrWqa1gT9Fwl239x-ZfN1eqTD8a22gMH8zU

##Content-Type: application/json
##Authorization: Bearer {{accessToken}}

POST {{base}}api/v1/auth/sign-in
Content-Type: application/json

{
    "first_name":"Bore",
    "last_name":"Gona",
    "email": "helubore2@gmail.com",
    "password": "123456789"
}

### create project

POST {{base}}api/v1/projects
Authorization: Bearer {{a_token}}

{
    "project_name": "Getting Things Done App",
    "description":"Build the gtd app for productivity",
    "outcome":"Completed and deployed",
    "priority": "High",
    "status":"Pending"
}